### ISSUE TITLE
Can this code work with the Genderize.io bigger batch key?

### ISSUE THREAD

**Issue by 13bzhang** [SteelPangolin/genderize#3]
I recently purchased the Genderize.io 100,000 a month key. Can `genderize` work with the key? I don't know where to put the key in the `get` function. Thanks!

**Comment by SteelPangolin** [comment]
Not yet. I wasn't aware of this feature until you emailed me.

**Comment by SteelPangolin** [comment]
Please file a bug on the project and I'll see if I can add it.

**Comment by SteelPangolin** [comment]
@Stroemgren: can you issue me a test key for the paid version of the Genderize service?

**Comment by SteelPangolin** [comment]
@13bzhang: Try the new release 0.1.4 and let me know if you have any trouble.
