### ISSUE TITLE
It used to work but now I get “SSL: CERTIFICATE_VERIFY_FAILED” Error

### ISSUE THREAD

**Issue by sionking** [SteelPangolin/genderize#7]
I use it ~700 times a day with 1 name each time.
What can I do to solve it ?

**Comment by SteelPangolin** [comment]
What operating system and Python version are you using, how did you install Python, and have you read [this note on Python 3.6 on macOS](https://stackoverflow.com/a/42334357) if it applies to you?

**Comment by SteelPangolin** [comment]
Cannot repro this without more information, and the likely causes are all related to Python environment setup outside the control of this package. Closing.
