### ISSUE TITLE
Process stuck on windows

### ISSUE THREAD

**Issue by sionking** [SteelPangolin/genderize#8]
logger.info("Start the genderize api")
        gen = (Genderize().get(names=[name_lowercase]))
        logger.info("end the genderize api")

The first line is set but we don't reach the second one, ctrl+c don't even close the process!
Is it that something is stuck ?

**Comment by sionking** [comment]
I think that no timeout set for socket connection

**Comment by SteelPangolin** [comment]
Adding support for timeouts in v0.3.0, which will default to 30 seconds.
